### ISSUE TITLE
Incapable of deleting a job when a single one is running

### ISSUE THREAD

**Issue by cacof1** [clulab/qup#1]
When a single job is running, trying the qdel function leads to the following error:

Exception in thread "handler-10" java.lang.IndexOutOfBoundsException: 0
        at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
        at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
        at main.scala.qup.scheduler.SchedulerExecutor.findJob(SchedulerExecutor.scala:183)
        at main.scala.qup.scheduler.SchedulerExecutor.deleteJob(SchedulerExecutor.scala:114)
        at main.scala.qup.scheduler.SchedulerServer.run(SchedulerServer.scala:62)
        at java.base/java.lang.Thread.run(Thread.java:829)

It seems the findJob at this line is failing to find any object and searching for the zero-th returns an out of bound error:
    // Step 2: Search running jobs
    if (runningJobs.filter(_.id == jobID).length != 0) {
      return Some( runningJobs.filter(_.id != jobID)(0) )
    }

SchedulerExecutorScala.

**Comment by PeterAJansen** [comment]
Thanks for this bug report!  I'm currently traveling for the winter break here, and away from my normal development machine.  I may not be able to get to this bug for about two weeks, unless it's urgent?

**Comment by cacof1** [comment]
Absolutely no problem ofc! Let me know when you have had a chance to look into it?

**Comment by cacof1** [comment]
Sorry to bother you, but is there any updates regarding this issue?

Thank you very much.

Charles

**Comment by PeterAJansen** [comment]
Thanks again @cacof1 for submitting this bug! It turns out the `!=` on that line should have been `==`.  

I've just pushed a fix to the main branch, so if you reclone and reinstall (`sudo ./install.sh`), it should update without issue. 

I've also changed the build manager to SBT, so if there are any additional customizations that you find yourself wanting (that you don't want to submit a feature request for), repackaging should be as simple as running `./package.sh` followed by `./install. sh`. 

I'd also like to thank you for submitting this bug report -- I'd noticed something was wonky with job deletion but I couldn't put my finger on it, since my test had multiple jobs.  I had initially planned on adding pre-emptable jobs, but since the job deletion wasn't 100%, I held off on that feature.  Now if I get a bit of time, I can hopefully add that one day. :)
